import { CountryData, Transaction } from './types';

export const SAVING_GOALS = [
  { id: 'home', label: 'Buy a Home', icon: '🏠' },
  { id: 'vehicle', label: 'Buy a Vehicle', icon: '🚗' },
  { id: 'education', label: 'Education', icon: '🎓' },
  { id: 'retirement', label: 'Retirement', icon: '👴' },
  { id: 'travel', label: 'Travel', icon: '✈️' },
  { id: 'emergency', label: 'Emergency Fund', icon: '🛡️' },
  { id: 'wedding', label: 'Wedding', icon: '💍' },
  { id: 'gadgets', label: 'Gadgets', icon: '📱' },
  { id: 'business', label: 'Start Business', icon: '💼' },
  { id: 'investment', label: 'Wealth Building', icon: '📈' },
];

export const ECONOMIC_NEWS = [
  { id: 1, title: "Global Markets Rally as Inflation Data Cools", source: "Financial Times", time: "2h ago", url: "https://www.ft.com" },
  { id: 2, title: "Central Banks Signal Potential Rate Cuts in Q4", source: "Bloomberg", time: "4h ago", url: "https://www.bloomberg.com" },
  { id: 3, title: "Tech Stocks Surge on AI Advancements", source: "Reuters", time: "5h ago", url: "https://www.reuters.com" },
  { id: 4, title: "Oil Prices Stabilize Amidst Supply Chain Adjustments", source: "WSJ", time: "6h ago", url: "https://www.wsj.com" },
  { id: 5, title: "Emerging Markets Show Resilience Against Dollar Strength", source: "CNBC", time: "8h ago", url: "https://www.cnbc.com" },
  { id: 6, title: "Cryptocurrency Regulation Talks Heat Up in G20 Summit", source: "Coindesk", time: "10h ago", url: "https://www.coindesk.com" },
];

// A comprehensive list covering ~195 countries/territories
export const COUNTRIES: CountryData[] = [
  { name: "Afghanistan", code: "AF", dial_code: "+93", flag: "🇦🇫", digits: [9] },
  { name: "Albania", code: "AL", dial_code: "+355", flag: "🇦🇱", digits: [9] },
  { name: "Algeria", code: "DZ", dial_code: "+213", flag: "🇩🇿", digits: [9, 10] },
  { name: "Andorra", code: "AD", dial_code: "+376", flag: "🇦🇩", digits: [6] },
  { name: "Angola", code: "AO", dial_code: "+244", flag: "🇦🇴", digits: [9] },
  { name: "Antigua and Barbuda", code: "AG", dial_code: "+1-268", flag: "🇦🇬", digits: [7] },
  { name: "Argentina", code: "AR", dial_code: "+54", flag: "🇦🇷", digits: [10, 11] },
  { name: "Armenia", code: "AM", dial_code: "+374", flag: "🇦🇲", digits: [8] },
  { name: "Australia", code: "AU", dial_code: "+61", flag: "🇦🇺", digits: [9] },
  { name: "Austria", code: "AT", dial_code: "+43", flag: "🇦🇹", digits: [10, 11, 12] },
  { name: "Azerbaijan", code: "AZ", dial_code: "+994", flag: "🇦🇿", digits: [9] },
  { name: "Bahamas", code: "BS", dial_code: "+1-242", flag: "🇧🇸", digits: [7] },
  { name: "Bahrain", code: "BH", dial_code: "+973", flag: "🇧🇭", digits: [8] },
  { name: "Bangladesh", code: "BD", dial_code: "+880", flag: "🇧🇩", digits: [10] },
  { name: "Barbados", code: "BB", dial_code: "+1-246", flag: "🇧🇧", digits: [7] },
  { name: "Belarus", code: "BY", dial_code: "+375", flag: "🇧🇾", digits: [9] },
  { name: "Belgium", code: "BE", dial_code: "+32", flag: "🇧🇪", digits: [9] },
  { name: "Belize", code: "BZ", dial_code: "+501", flag: "🇧🇿", digits: [7] },
  { name: "Benin", code: "BJ", dial_code: "+229", flag: "🇧🇯", digits: [8] },
  { name: "Bhutan", code: "BT", dial_code: "+975", flag: "🇧🇹", digits: [8] },
  { name: "Bolivia", code: "BO", dial_code: "+591", flag: "🇧🇴", digits: [8] },
  { name: "Bosnia and Herzegovina", code: "BA", dial_code: "+387", flag: "🇧🇦", digits: [8] },
  { name: "Botswana", code: "BW", dial_code: "+267", flag: "🇧🇼", digits: [7, 8] },
  { name: "Brazil", code: "BR", dial_code: "+55", flag: "🇧🇷", digits: [10, 11] },
  { name: "Brunei", code: "BN", dial_code: "+673", flag: "🇧🇳", digits: [7] },
  { name: "Bulgaria", code: "BG", dial_code: "+359", flag: "🇧🇬", digits: [8, 9] },
  { name: "Burkina Faso", code: "BF", dial_code: "+226", flag: "🇧🇫", digits: [8] },
  { name: "Burundi", code: "BI", dial_code: "+257", flag: "🇧🇮", digits: [8] },
  { name: "Cambodia", code: "KH", dial_code: "+855", flag: "🇰🇭", digits: [8, 9] },
  { name: "Cameroon", code: "CM", dial_code: "+237", flag: "🇨🇲", digits: [9] },
  { name: "Canada", code: "CA", dial_code: "+1", flag: "🇨🇦", digits: [10] },
  { name: "Cape Verde", code: "CV", dial_code: "+238", flag: "🇨🇻", digits: [7] },
  { name: "Central African Republic", code: "CF", dial_code: "+236", flag: "🇨🇫", digits: [8] },
  { name: "Chad", code: "TD", dial_code: "+235", flag: "🇹🇩", digits: [8] },
  { name: "Chile", code: "CL", dial_code: "+56", flag: "🇨🇱", digits: [9] },
  { name: "China", code: "CN", dial_code: "+86", flag: "🇨🇳", digits: [11] },
  { name: "Colombia", code: "CO", dial_code: "+57", flag: "🇨🇴", digits: [10] },
  { name: "Comoros", code: "KM", dial_code: "+269", flag: "🇰🇲", digits: [7] },
  { name: "Congo (DRC)", code: "CD", dial_code: "+243", flag: "🇨🇩", digits: [9] },
  { name: "Congo (Republic)", code: "CG", dial_code: "+242", flag: "🇨🇬", digits: [9] },
  { name: "Costa Rica", code: "CR", dial_code: "+506", flag: "🇨🇷", digits: [8] },
  { name: "Croatia", code: "HR", dial_code: "+385", flag: "🇭🇷", digits: [8, 9] },
  { name: "Cuba", code: "CU", dial_code: "+53", flag: "🇨🇺", digits: [8] },
  { name: "Cyprus", code: "CY", dial_code: "+357", flag: "🇨🇾", digits: [8] },
  { name: "Czech Republic", code: "CZ", dial_code: "+420", flag: "🇨🇿", digits: [9] },
  { name: "Denmark", code: "DK", dial_code: "+45", flag: "🇩🇰", digits: [8] },
  { name: "Djibouti", code: "DJ", dial_code: "+253", flag: "🇩🇯", digits: [8] },
  { name: "Dominica", code: "DM", dial_code: "+1-767", flag: "🇩🇲", digits: [7] },
  { name: "Dominican Republic", code: "DO", dial_code: "+1", flag: "🇩🇴", digits: [10] },
  { name: "Ecuador", code: "EC", dial_code: "+593", flag: "🇪🇨", digits: [9] },
  { name: "Egypt", code: "EG", dial_code: "+20", flag: "🇪🇬", digits: [10, 11] },
  { name: "El Salvador", code: "SV", dial_code: "+503", flag: "🇸🇻", digits: [8] },
  { name: "Equatorial Guinea", code: "GQ", dial_code: "+240", flag: "🇬🇶", digits: [9] },
  { name: "Eritrea", code: "ER", dial_code: "+291", flag: "🇪🇷", digits: [7] },
  { name: "Estonia", code: "EE", dial_code: "+372", flag: "🇪🇪", digits: [7, 8] },
  { name: "Eswatini", code: "SZ", dial_code: "+268", flag: "🇸🇿", digits: [8] },
  { name: "Ethiopia", code: "ET", dial_code: "+251", flag: "🇪🇹", digits: [9] },
  { name: "Fiji", code: "FJ", dial_code: "+679", flag: "🇫🇯", digits: [7] },
  { name: "Finland", code: "FI", dial_code: "+358", flag: "🇫🇮", digits: [5, 6, 7, 8, 9, 10] },
  { name: "France", code: "FR", dial_code: "+33", flag: "🇫🇷", digits: [9] },
  { name: "Gabon", code: "GA", dial_code: "+241", flag: "🇬🇦", digits: [7, 8] },
  { name: "Gambia", code: "GM", dial_code: "+220", flag: "🇬🇲", digits: [7] },
  { name: "Georgia", code: "GE", dial_code: "+995", flag: "🇬🇪", digits: [9] },
  { name: "Germany", code: "DE", dial_code: "+49", flag: "🇩🇪", digits: [10, 11] },
  { name: "Ghana", code: "GH", dial_code: "+233", flag: "🇬🇭", digits: [9] },
  { name: "Greece", code: "GR", dial_code: "+30", flag: "🇬🇷", digits: [10] },
  { name: "Grenada", code: "GD", dial_code: "+1-473", flag: "🇬🇩", digits: [7] },
  { name: "Guatemala", code: "GT", dial_code: "+502", flag: "🇬🇹", digits: [8] },
  { name: "Guinea", code: "GN", dial_code: "+224", flag: "🇬🇳", digits: [9] },
  { name: "Guinea-Bissau", code: "GW", dial_code: "+245", flag: "🇬🇼", digits: [7, 9] },
  { name: "Guyana", code: "GY", dial_code: "+592", flag: "🇬🇾", digits: [7] },
  { name: "Haiti", code: "HT", dial_code: "+509", flag: "🇭🇹", digits: [8] },
  { name: "Honduras", code: "HN", dial_code: "+504", flag: "🇭🇳", digits: [8] },
  { name: "Hungary", code: "HU", dial_code: "+36", flag: "🇭🇺", digits: [9] },
  { name: "Iceland", code: "IS", dial_code: "+354", flag: "🇮🇸", digits: [7] },
  { name: "India", code: "IN", dial_code: "+91", flag: "🇮🇳", digits: [10] },
  { name: "Indonesia", code: "ID", dial_code: "+62", flag: "🇮🇩", digits: [10, 11, 12] },
  { name: "Iran", code: "IR", dial_code: "+98", flag: "🇮🇷", digits: [10] },
  { name: "Iraq", code: "IQ", dial_code: "+964", flag: "🇮🇶", digits: [10] },
  { name: "Ireland", code: "IE", dial_code: "+353", flag: "🇮🇪", digits: [9] },
  { name: "Israel", code: "IL", dial_code: "+972", flag: "🇮🇱", digits: [9] },
  { name: "Italy", code: "IT", dial_code: "+39", flag: "🇮🇹", digits: [10] },
  { name: "Jamaica", code: "JM", dial_code: "+1-876", flag: "🇯🇲", digits: [7] },
  { name: "Japan", code: "JP", dial_code: "+81", flag: "🇯🇵", digits: [10] },
  { name: "Jordan", code: "JO", dial_code: "+962", flag: "🇯🇴", digits: [9] },
  { name: "Kazakhstan", code: "KZ", dial_code: "+7", flag: "🇰🇿", digits: [10] },
  { name: "Kenya", code: "KE", dial_code: "+254", flag: "🇰🇪", digits: [9] },
  { name: "Kiribati", code: "KI", dial_code: "+686", flag: "🇰🇮", digits: [8] },
  { name: "Kuwait", code: "KW", dial_code: "+965", flag: "🇰🇼", digits: [8] },
  { name: "Kyrgyzstan", code: "KG", dial_code: "+996", flag: "🇰🇬", digits: [9] },
  { name: "Laos", code: "LA", dial_code: "+856", flag: "🇱🇦", digits: [9, 10] },
  { name: "Latvia", code: "LV", dial_code: "+371", flag: "🇱🇻", digits: [8] },
  { name: "Lebanon", code: "LB", dial_code: "+961", flag: "🇱🇧", digits: [7, 8] },
  { name: "Lesotho", code: "LS", dial_code: "+266", flag: "🇱🇸", digits: [8] },
  { name: "Liberia", code: "LR", dial_code: "+231", flag: "🇱🇷", digits: [8, 9] },
  { name: "Libya", code: "LY", dial_code: "+218", flag: "🇱🇾", digits: [9] },
  { name: "Liechtenstein", code: "LI", dial_code: "+423", flag: "🇱🇮", digits: [7] },
  { name: "Lithuania", code: "LT", dial_code: "+370", flag: "🇱🇹", digits: [8] },
  { name: "Luxembourg", code: "LU", dial_code: "+352", flag: "🇱🇺", digits: [9] },
  { name: "Madagascar", code: "MG", dial_code: "+261", flag: "🇲🇬", digits: [9] },
  { name: "Malawi", code: "MW", dial_code: "+265", flag: "🇲🇼", digits: [9] },
  { name: "Malaysia", code: "MY", dial_code: "+60", flag: "🇲🇾", digits: [9, 10] },
  { name: "Maldives", code: "MV", dial_code: "+960", flag: "🇲🇻", digits: [7] },
  { name: "Mali", code: "ML", dial_code: "+223", flag: "🇲🇱", digits: [8] },
  { name: "Malta", code: "MT", dial_code: "+356", flag: "🇲🇹", digits: [8] },
  { name: "Marshall Islands", code: "MH", dial_code: "+692", flag: "🇲🇭", digits: [7] },
  { name: "Mauritania", code: "MR", dial_code: "+222", flag: "🇲🇷", digits: [8] },
  { name: "Mauritius", code: "MU", dial_code: "+230", flag: "🇲🇺", digits: [8] },
  { name: "Mexico", code: "MX", dial_code: "+52", flag: "🇲🇽", digits: [10] },
  { name: "Micronesia", code: "FM", dial_code: "+691", flag: "🇫🇲", digits: [7] },
  { name: "Moldova", code: "MD", dial_code: "+373", flag: "🇲🇩", digits: [8] },
  { name: "Monaco", code: "MC", dial_code: "+377", flag: "🇲🇨", digits: [8, 9] },
  { name: "Mongolia", code: "MN", dial_code: "+976", flag: "🇲🇳", digits: [8] },
  { name: "Montenegro", code: "ME", dial_code: "+382", flag: "🇲🇪", digits: [8] },
  { name: "Morocco", code: "MA", dial_code: "+212", flag: "🇲🇦", digits: [9] },
  { name: "Mozambique", code: "MZ", dial_code: "+258", flag: "🇲🇿", digits: [9] },
  { name: "Myanmar", code: "MM", dial_code: "+95", flag: "🇲🇲", digits: [9] },
  { name: "Namibia", code: "NA", dial_code: "+264", flag: "🇳🇦", digits: [9] },
  { name: "Nauru", code: "NR", dial_code: "+674", flag: "🇳🇷", digits: [7] },
  { name: "Nepal", code: "NP", dial_code: "+977", flag: "🇳🇵", digits: [10] },
  { name: "Netherlands", code: "NL", dial_code: "+31", flag: "🇳🇱", digits: [9] },
  { name: "New Zealand", code: "NZ", dial_code: "+64", flag: "🇳🇿", digits: [9] },
  { name: "Nicaragua", code: "NI", dial_code: "+505", flag: "🇳🇮", digits: [8] },
  { name: "Niger", code: "NE", dial_code: "+227", flag: "🇳🇪", digits: [8] },
  { name: "Nigeria", code: "NG", dial_code: "+234", flag: "🇳🇬", digits: [10] },
  { name: "North Korea", code: "KP", dial_code: "+850", flag: "🇰🇵", digits: [10] },
  { name: "North Macedonia", code: "MK", dial_code: "+389", flag: "🇲🇰", digits: [8] },
  { name: "Norway", code: "NO", dial_code: "+47", flag: "🇳🇴", digits: [8] },
  { name: "Oman", code: "OM", dial_code: "+968", flag: "🇴🇲", digits: [8] },
  { name: "Pakistan", code: "PK", dial_code: "+92", flag: "🇵🇰", digits: [10] },
  { name: "Palau", code: "PW", dial_code: "+680", flag: "🇵🇼", digits: [7] },
  { name: "Palestine", code: "PS", dial_code: "+970", flag: "🇵🇸", digits: [9] },
  { name: "Panama", code: "PA", dial_code: "+507", flag: "🇵🇦", digits: [7, 8] },
  { name: "Papua New Guinea", code: "PG", dial_code: "+675", flag: "🇵🇬", digits: [8] },
  { name: "Paraguay", code: "PY", dial_code: "+595", flag: "🇵🇾", digits: [9] },
  { name: "Peru", code: "PE", dial_code: "+51", flag: "🇵🇪", digits: [9] },
  { name: "Philippines", code: "PH", dial_code: "+63", flag: "🇵🇭", digits: [10] },
  { name: "Poland", code: "PL", dial_code: "+48", flag: "🇵🇱", digits: [9] },
  { name: "Portugal", code: "PT", dial_code: "+351", flag: "🇵🇹", digits: [9] },
  { name: "Qatar", code: "QA", dial_code: "+974", flag: "🇶🇦", digits: [8] },
  { name: "Romania", code: "RO", dial_code: "+40", flag: "🇷🇴", digits: [9] },
  { name: "Russia", code: "RU", dial_code: "+7", flag: "🇷🇺", digits: [10] },
  { name: "Rwanda", code: "RW", dial_code: "+250", flag: "🇷🇼", digits: [9] },
  { name: "Saint Kitts and Nevis", code: "KN", dial_code: "+1-869", flag: "🇰🇳", digits: [7] },
  { name: "Saint Lucia", code: "LC", dial_code: "+1-758", flag: "🇱🇨", digits: [7] },
  { name: "Saint Vincent and the Grenadines", code: "VC", dial_code: "+1-784", flag: "🇻🇨", digits: [7] },
  { name: "Samoa", code: "WS", dial_code: "+685", flag: "🇼🇸", digits: [7] },
  { name: "San Marino", code: "SM", dial_code: "+378", flag: "🇸🇲", digits: [6, 7, 8, 9, 10] },
  { name: "Sao Tome and Principe", code: "ST", dial_code: "+239", flag: "🇸🇹", digits: [7] },
  { name: "Saudi Arabia", code: "SA", dial_code: "+966", flag: "🇸🇦", digits: [9] },
  { name: "Senegal", code: "SN", dial_code: "+221", flag: "🇸🇳", digits: [9] },
  { name: "Serbia", code: "RS", dial_code: "+381", flag: "🇷🇸", digits: [8, 9] },
  { name: "Seychelles", code: "SC", dial_code: "+248", flag: "🇸🇨", digits: [7] },
  { name: "Sierra Leone", code: "SL", dial_code: "+232", flag: "🇸🇱", digits: [8] },
  { name: "Singapore", code: "SG", dial_code: "+65", flag: "🇸🇬", digits: [8] },
  { name: "Slovakia", code: "SK", dial_code: "+421", flag: "🇸🇰", digits: [9] },
  { name: "Slovenia", code: "SI", dial_code: "+386", flag: "🇸🇮", digits: [8] },
  { name: "Solomon Islands", code: "SB", dial_code: "+677", flag: "🇸🇧", digits: [7] },
  { name: "Somalia", code: "SO", dial_code: "+252", flag: "🇸🇴", digits: [8] },
  { name: "South Africa", code: "ZA", dial_code: "+27", flag: "🇿🇦", digits: [9] },
  { name: "South Korea", code: "KR", dial_code: "+82", flag: "🇰🇷", digits: [9, 10] },
  { name: "South Sudan", code: "SS", dial_code: "+211", flag: "🇸🇸", digits: [9] },
  { name: "Spain", code: "ES", dial_code: "+34", flag: "🇪🇸", digits: [9] },
  { name: "Sri Lanka", code: "LK", dial_code: "+94", flag: "🇱🇰", digits: [9] },
  { name: "Sudan", code: "SD", dial_code: "+249", flag: "🇸🇩", digits: [9] },
  { name: "Suriname", code: "SR", dial_code: "+597", flag: "🇸🇷", digits: [6, 7] },
  { name: "Sweden", code: "SE", dial_code: "+46", flag: "🇸🇪", digits: [9] },
  { name: "Switzerland", code: "CH", dial_code: "+41", flag: "🇨🇭", digits: [9] },
  { name: "Syria", code: "SY", dial_code: "+963", flag: "🇸🇾", digits: [9] },
  { name: "Taiwan", code: "TW", dial_code: "+886", flag: "🇹🇼", digits: [9] },
  { name: "Tajikistan", code: "TJ", dial_code: "+992", flag: "🇹🇯", digits: [9] },
  { name: "Tanzania", code: "TZ", dial_code: "+255", flag: "🇹🇿", digits: [9] },
  { name: "Thailand", code: "TH", dial_code: "+66", flag: "🇹🇭", digits: [9] },
  { name: "Timor-Leste", code: "TL", dial_code: "+670", flag: "🇹🇱", digits: [8] },
  { name: "Togo", code: "TG", dial_code: "+228", flag: "🇹🇬", digits: [8] },
  { name: "Tonga", code: "TO", dial_code: "+676", flag: "🇹🇴", digits: [5, 6, 7] },
  { name: "Trinidad and Tobago", code: "TT", dial_code: "+1-868", flag: "🇹🇹", digits: [7] },
  { name: "Tunisia", code: "TN", dial_code: "+216", flag: "🇹🇳", digits: [8] },
  { name: "Turkey", code: "TR", dial_code: "+90", flag: "🇹🇷", digits: [10] },
  { name: "Turkmenistan", code: "TM", dial_code: "+993", flag: "🇹🇲", digits: [8] },
  { name: "Tuvalu", code: "TV", dial_code: "+688", flag: "🇹🇻", digits: [5, 6] },
  { name: "Uganda", code: "UG", dial_code: "+256", flag: "🇺🇬", digits: [9] },
  { name: "Ukraine", code: "UA", dial_code: "+380", flag: "🇺🇦", digits: [9] },
  { name: "United Arab Emirates", code: "AE", dial_code: "+971", flag: "🇦🇪", digits: [9] },
  { name: "United Kingdom", code: "GB", dial_code: "+44", flag: "🇬🇧", digits: [10, 11] },
  { name: "United States", code: "US", dial_code: "+1", flag: "🇺🇸", digits: [10] },
  { name: "Uruguay", code: "UY", dial_code: "+598", flag: "🇺🇾", digits: [8] },
  { name: "Uzbekistan", code: "UZ", dial_code: "+998", flag: "🇺🇿", digits: [9] },
  { name: "Vanuatu", code: "VU", dial_code: "+678", flag: "🇻🇺", digits: [7] },
  { name: "Vatican City", code: "VA", dial_code: "+39", flag: "🇻🇦", digits: [10] },
  { name: "Venezuela", code: "VE", dial_code: "+58", flag: "🇻🇪", digits: [10] },
  { name: "Vietnam", code: "VN", dial_code: "+84", flag: "🇻🇳", digits: [9, 10] },
  { name: "Yemen", code: "YE", dial_code: "+967", flag: "🇾🇪", digits: [9] },
  { name: "Zambia", code: "ZM", dial_code: "+260", flag: "🇿🇲", digits: [9] },
  { name: "Zimbabwe", code: "ZW", dial_code: "+263", flag: "🇿🇼", digits: [9] },
];

export const PROFESSIONS = [
  "Student",
  "Engineer",
  "Doctor",
  "Teacher",
  "Artist",
  "Entrepreneur",
  "Lawyer",
  "Accountant",
  "Architect",
  "Consultant",
  "Nurse",
  "Sales Professional",
  "Marketing Specialist",
  "Software Developer",
  "Data Scientist",
  "Researcher",
  "Business Analyst",
  "Freelancer",
  "Other"
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: '1', amount: 5000, category: 'Salary', date: '2023-10-01', type: 'income', description: 'Monthly Salary' },
  { id: '2', amount: 120, category: 'Food', date: '2023-10-02', type: 'expense', description: 'Grocery Store' },
  { id: '3', amount: 45, category: 'Transport', date: '2023-10-03', type: 'expense', description: 'Uber Ride' },
  { id: '4', amount: 200, category: 'Utilities', date: '2023-10-05', type: 'expense', description: 'Electric Bill' },
  { id: '5', amount: 1500, category: 'Freelance', date: '2023-10-10', type: 'income', description: 'Web Design Project' },
  { id: '6', amount: 80, category: 'Entertainment', date: '2023-10-12', type: 'expense', description: 'Cinema & Snacks' },
];